#!/bin/sh

case "$1" in

	""|start|restart|stop)
		exit 0
		;;

	info)
        echo "Info: <b>WebAPI</b>"
        echo "Name: WebAPI"
        echo "Version: 1.0"
        echo "Operations: uninstall"
        ;;
	uninstall)
		rm -r /usr/local/etc/config/addons/www/webapi
		;;
	*)
        echo "Usage: hq-webapi {info|uninstall}" >&2
        exit 1
        ;;

esac

exit 0
